### ISSUE TITLE
[Bug]: Undefined array key "request"

### ISSUE THREAD

**Issue by moghwan** [paulo-hortelan/requests-graph-pulse#1]
### What happened?

after installing and registering the package and the recorder, the card loads with the error **[Bug]: Undefined array key "request"**

![image](https://github.com/paulo-hortelan/requests-graph-pulse/assets/2495180/928f47f0-7cc6-41e0-a1c5-00a115553f8d)

### How to reproduce the bug

opening laravel pulse triggers the error

### Package Version

1.0.4

### PHP Version

8.2.14

### Laravel Version

10.39.0

### Which operating systems does with happen with?

Linux

### Notes

using laravel sail 1.26

**Comment by paulo-hortelan** [comment]
This error was happening when there was no request recorded. 

Thank you for pointing it out, It should be fixed with the latest version **v1.0.5**

I'll leave the issue open for a few days just in case
