### ISSUE TITLE
[Bug]: No color for Informational requests

### ISSUE THREAD

**Issue by maciek-szn** [paulo-hortelan/requests-graph-pulse#12]
### What happened?

In the chart header there is no line shown for the Informational requests.

![obraz](https://github.com/user-attachments/assets/fcbe46b4-16bb-4d39-849a-abb2bbb59cb6)
![obraz](https://github.com/user-attachments/assets/bd1c4050-7080-43e6-aaac-75f84be03dfd)

CSS class for this line is `bg-[rgba(29,153,172,0.5)]`, but it doesn't seem to be defined.

![obraz](https://github.com/user-attachments/assets/35b5e986-758f-4923-a73d-fc20cea46845)

### How to reproduce the bug

In `pulse.php` file change the setting `record_informational` for `RequestsGraphRecorder` from `false` to `true` and observe the chart header.

### Package Version

1.2

### PHP Version

8.3.10

### Laravel Version

10.48.20

### Which operating systems does with happen with?

Windows

**Comment by paulo-hortelan** [comment]
Looks like some tailwind problem, I tried to change from rgba to hex but it makes no difference.

As soon as possible I'll look into it. Be free to send PR 😁

Thank you for reporting

**Comment by maciek-szn** [comment]
It seems that Pulse ships with some set of CSS classes by default, but if you want to use something else, you need to define it somehow.

I'll create a PR for this

**Comment by paulo-hortelan** [comment]
Perfect! Thank you for contributing
