### ISSUE TITLE
[Feature Request]: Show number of request on hover

### ISSUE THREAD

**Issue by jhm-ciberman** [paulo-hortelan/requests-graph-pulse#8]
### What happened?

I just deployed this awesome package to production, and it is great! Thanks for the amazing work. 

I would like to request if it would be possible to show the number of requests when hovering the mouse. Currently only the max value is shown:

![image](https://github.com/paulo-hortelan/requests-graph-pulse/assets/7988351/84c8821a-067d-4b35-9a8d-9d061f06038d)

Other native charts like the Queues chart or the memory usage chart do display the number when hovering:

![image](https://github.com/paulo-hortelan/requests-graph-pulse/assets/7988351/e7b46029-085a-4757-a597-253812dbc21b)

### How to reproduce the bug

.

### Package Version

1.1

### PHP Version

8.3

### Laravel Version

11

**Comment by paulo-hortelan** [comment]
Hello and thank you for using my package.

This feature already exists and it's working properly on my projects: 

![image](https://github.com/paulo-hortelan/requests-graph-pulse/assets/135706260/492b373f-869f-41df-ab16-b00da907dbc4)

However I'm using only Laravel 10, so maybe this is a bug for Laravel 11.

 I'll try to reproduce and fix it, but PR are always welcome. Thank you for reporting

**Comment by jhm-ciberman** [comment]
Oh, weird. for me it shows only the number of non 2XX requests:

![image](https://github.com/paulo-hortelan/requests-graph-pulse/assets/7988351/ae43d482-be7a-48c3-b149-7edb9e66a3c6)

This is my `artisan about` in my prod environment:

```
forge@XXXXXXXXXX:~/XXXXXXXXX$ php artisan about

  Environment ........................................................................................................
  Application Name ........................................................................................ XXXXXXXXX
  Laravel Version ............................................................................................. 11.6.0
  PHP Version ................................................................... 8.3.3-1+ubuntu22.04.1+deb.sury.org+1
  Composer Version ............................................................................................. 2.7.6
  Environment ............................................................................................. production
  Debug Mode ..................................................................................................... OFF
  URL ............................................................................................. XXXXXXXXXX
  Maintenance Mode ............................................................................................... OFF

  Cache ..............................................................................................................
  Config ...................................................................................................... CACHED
  Events ...................................................................................................... CACHED
  Routes ...................................................................................................... CACHED
  Views ....................................................................................................... CACHED

  Drivers ............................................................................................................
  Broadcasting .................................................................................................. null
  Cache ........................................................................................................ redis
  Database ..................................................................................................... pgsql
  Logs ......................................................................................................... daily
  Mail ...................................................................................................... postmark
  Queue ........................................................................................................ redis
  Session ....................................................................................................... file

  Pulse ..............................................................................................................
  Enabled .................................................................................................... ENABLED
  Version .............................................................................................. v1.0.0-beta16

  Livewire ...........................................................................................................
  Livewire ................................................................................................... v3.4.10
```

**Comment by jhm-ciberman** [comment]
I'm wondering. Could it be that numbers greater than 100 are not shown?

**Comment by paulo-hortelan** [comment]
Don't think so, in my production environment on the last 7 days we have this:

![image](https://github.com/paulo-hortelan/requests-graph-pulse/assets/135706260/dfabf245-4634-4b41-b87e-d258c0f0ce7b)

Can you create the same scenario using Laravel 10 instead of the 11?

**Comment by maciek-szn** [comment]
> I'm wondering. Could it be that numbers greater than 100 are not shown?

I see this issue with values over 10000.

![obraz](https://github.com/user-attachments/assets/4cfb08b0-74ed-4c31-a5ce-c976768ae9b4)

![obraz](https://github.com/user-attachments/assets/a691a92b-2f65-493c-8bca-aea51806fa66)
